/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false` (hash: f481048acb7aef2b0c081f9b6a4eee8e)
interface __BaseEnv_Env {
	FILES: R2Bucket;
	DB: D1Database;
	AI: Ai;
	ASSETS: Fetcher;
	BETTER_AUTH_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	JUDGE0_KEY: string;
	APP_ORIGIN: string;
	AI_GATEWAY_ID: string;
	AI_MODEL: string;
	JUDGE0_URL: string;
	JUDGE0_HOST: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface ProductionEnv {
		FILES: R2Bucket;
		DB: D1Database;
		AI: Ai;
		ASSETS: Fetcher;
		BETTER_AUTH_SECRET: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		JUDGE0_KEY: string;
		APP_ORIGIN: string;
		AI_GATEWAY_ID: string;
		AI_MODEL: string;
		JUDGE0_URL: string;
		JUDGE0_HOST: string;
	}
	interface StagingEnv {
		FILES: R2Bucket;
		DB: D1Database;
		AI: Ai;
		ASSETS: Fetcher;
		BETTER_AUTH_SECRET: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		JUDGE0_KEY: string;
		APP_ORIGIN: string;
		AI_GATEWAY_ID: string;
		AI_MODEL: string;
		JUDGE0_URL: string;
		JUDGE0_HOST: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_SECRET" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "JUDGE0_KEY" | "APP_ORIGIN" | "AI_GATEWAY_ID" | "AI_MODEL" | "JUDGE0_URL" | "JUDGE0_HOST">> {}
}
